### ISSUE TITLE
vagrant auto network

### ISSUE THREAD

**Issue by OwenBrotherwood** [bfayers/microbit-vagrants#9]
https://github.com/oscar-stack/vagrant-auto_network

At some stage, find out the pros and cons

Note related to needing elevated priviledges

**Comment by OwenBrotherwood** [comment]
Also Jonny comment about nfs and need for elevated priviledges.
Shared folders are ok, but many people would prefer to scp contra let elevated priviledges take over their machine.
https://github.com/bfayers/microbit-vagrants/blob/15a06d6e024e366936858bcb17a8d0fc462ee037/micropython/Vagrantfile#L43-L53

**Comment by jaustin** [comment]
So, in summary: I tend to prefer not to use things on OS X that need root, and autonetwork and NFS does require that. It looks like, at least in the PXT file the only reason for the autonetwork plugin was to make NFS trivially available.

There may be reasons the Espruino environment used NFS but I don't see that we'll be making heavy use of the FS sharing here (cloning is done inside the VM, for example) and so I'm keen to see how far we get with just vagrant's default sharing.

Things look to work okay with the NFS/autonetwork stuff hacked out, as per this Vagrantfile
[Vagrantfile.txt](https://github.com/bfayers/microbit-vagrants/files/699787/Vagrantfile.txt)

**Comment by OwenBrotherwood** [comment]
Closing as the intention is only to use privileged when needed and at the present time, not needed as hex can be downloaded in browser
